<a href="https://colab.research.google.com/github/DivyanshuTripathiCoder/DivyanshuTripathi/blob/main/numpy_learn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**NUMPY**

---



**Module:** organised prewritten code in a file.<br>
**Packages:** collection of modules and subpackages in a folder.<br>
**Libraries:** collection of modules and packages.<br>
**LIB. examples:**<br>

---


Numpy--> used to do mathematical operations on arrays and matrices.We can also do vectorised operations on matrices-->[1,2,3]*2=[2,4,6] but in normal python [1,2,3]*2=[1,2,3,1,2,3]<br>
Pandas-->stronger version of numpy.
<br><br>

---


Lets start with Numpy!!



In [2]:
#This is a termial command to install numpy but for accessing terminal here in code cell we use " ! "
!pip install numpy

In [3]:
#importing the numpy lib (abbrevating as "np")
import numpy as np
#checking the version of numpy
print(np.__version__)

2.0.2


In [4]:
#creating an array-- defining list and assigning it to numpy array
l=[1,2,3,4,5,6]
arr=np.array(l)
print("list is this : ",l)
print(type(l))
print("array is this : ",arr)
print(type(arr))

list is this :  [1, 2, 3, 4, 5, 6]
<class 'list'>
array is this :  [1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [5]:
#creating an array directly
a=np.array([1,3,5,7,9])
print(a)
print(type(a))
print(a.ndim)
print(a.shape)

[1 3 5 7 9]
<class 'numpy.ndarray'>
1
(5,)


**Ranges and Linespaces**

---


*   range ---->  np.arange(start, ending-1, step)
*   linespace-->np.linspace(starting_value, ending_value,number of values)






In [6]:
#for making range wali array by using "np.arange"
range_wali_array=np.arange(0,15,2)
print(range_wali_array)
#for making line space wali array using "np.linspace"
linespace_wali_array=  np.linspace(0,1,4)
print(linespace_wali_array)

[ 0  2  4  6  8 10 12 14]
[0.         0.33333333 0.66666667 1.        ]


**SPECIAL ARRAYS:** we can build any dim of array which have zeros anad ones only

---


*   zeros --> np.zeros((rows,coloumn))
*   ones  --> np.ones((rows,coloumn))


*   identity(square matrix)--> np.eye(rows **/** column)




In [7]:
#zeros wali array
zero_wali= np.zeros((3,3))
print(zero_wali)
print()
#one wali array
one_wali_array= np.ones((3,3))
print(one_wali_array)
print()
#identity
one_and_zero= np.eye(5)
print(one_and_zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
#RESHAPING AN ARRAY and FLATENING ARRAY
arr=np.arange(6)# making an array using arange function
print(arr) #printing the array
new=arr.reshape(2,3) #reshaping the array using reshape function
print(new) #printing the reshaped array
new_new=new.flatten() # flattening the reshaped array using flatten() function
print(new_new)#printing the flattned array

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


**MATHEMATICAL OPERATIONS:**



---







In [20]:
vals=np.array([4,9,16]) #making an array named as vals
vals= vals+2 #adding 1 to all the vals's element(vectorised operation),any operation can be done(+,-,*,**,/,//,%..).
print(vals) #printing the vals array
#---> some basic fun of operations : np.sqrt, np.power, np.add
print(np.sqrt(vals))# printing the sqrt using np.sqrt() function
print(np.power([vals],[2]))# printing the power using np.power([array],[power]) function
print(np.add([vals],[vals+1]))# printing the addition of 2 array using np.add([array],[array2]) function

[ 6 11 18]
[2.44948974 3.31662479 4.24264069]
[[ 36 121 324]]
[[13 23 37]]


**INDEXING AND FILTERING AND SORTING**

---



In [30]:
arr=np.array([1,5,7,2,8]) #creting an array
filtered=arr[arr>4]#putting the values bigger than 4 in a new var named filtered
print(filtered)# printing the filtered array
indices=np.where(arr>4) # putting the inxed of the elements greater than 4 into a var indices
print(indices)# printing all those indices
sorted=np.sort(arr)# sorting the array using np.sort(array) function
print("sorted array:",sorted)# printing the sorted array
arg_sort=np.argsort(arr)#sorting the indices and putting in a var named arg_sort using function -> np.argsort(array)
print("sorted indices:", arg_sort)#printing the sorted indices

[5 7 8]
(array([1, 2, 4]),)
sorted array: [1 2 5 7 8]
sorted indices: [0 3 1 2 4]
